{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  labels:
    {{- include "zkwasm-mini-service.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.secrets.keys.serverAdminKey }}: {{ .Values.secrets.serverAdminKey | b64enc }}
  {{ .Values.secrets.keys.settlerPrivateKey }}: {{ .Values.secrets.settlerPrivateKey | b64enc }}
{{- end }}
